// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzhegwhhsxwdfxwwjjur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6aGVnd2hoc3h3ZGZ4d3dqanVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzQzNjQsImV4cCI6MjA2MTExMDM2NH0.9Usj2LxNMmbpATCJ7LyKaqQw1aceo4L7jbuwDkDJPSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);